# Generated by Django 5.2.4 on 2025-09-15 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_route_api', '0002_alter_airplane_options_alter_airplanetype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user', 'flight'), name='unique_order_per_user_flight'),
        ),
    ]
