# Generated by Django 5.2.4 on 2025-09-15 17:27

import sky_route_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_route_api', '0003_order_unique_order_per_user_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sky_route_api.models.airport_image_file_path),
        ),
    ]
