# Generated by Django 5.2.4 on 2025-09-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky_route_api', '0004_airport_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_order_per_user_flight',
        ),
        migrations.RemoveField(
            model_name='order',
            name='flight',
        ),
    ]
